apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: activitytracker-pipeline
spec:
  params:
     - name: repository
       description: repository
     - name: revision
       description: the git repo branch
     - name: apikey
       description: apikey 
     - name: AT1
       description: AT
     - name: crn
       description: cos crn
  workspaces:
    - name: pipeline-pvc
  tasks:
    - name: activitytracker-task
      taskRef:
        name: activitytracker-task
      params:        
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision) 
        - name: apikey
          value: $(params.apikey)
        - name: AT1
          value: $(params.AT1)
        - name: crn
          value: $(params.crn)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
