apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: activitytracker-pipeline
spec:
  params:
     - name: repository
       description: repository
     - name: revision
       description: the git repo branch
     - name: apikey
       description: apikey 
     - name: resourcegroup
       description: resourcegroup
     - name: sshkey
       description: the sshkey
  workspaces:
    - name: pipeline-pvc
  tasks:
    - name: yathivpc
      taskRef:
        name: yathivpc
      params:        
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision) 
        - name: apikey
          value: $(params.apikey)
        - name: resourcegroup
          value: $(params.resourcegroup)
        - name: sshkey
          value: $(params.sshkey)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
