apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yathivpc-task
spec:
  params:
    - name: repository
      description: the git repository
    - name: sshkey
      description: the sshkey
    - name: resourcegroup
      description: the resource group
    - name: revision
      description: the revision
      default: main
    - name: apikey
      description: the ibmcloud api key
    - name: api
      description: the ibmcloud api endpoint
      default: "https://cloud.ibm.com"      
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: cd-secret
  workspaces:
    - name: task-pvc
      mountPath: /artifacts  
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: repository
          value: $(params.repository)
        - name: resourcegroup
          value: $(params.resourcegroup)
        - name: sshkey
          value: $(params.sshkey)
        - name: REVISION
          value: $(params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          url="https://github.com/aakuletiYatheesha/vpc.tekton.git" ;
          cd /workspace && git clone -q  $url .;

    - name: logscmd
      image: ibmcom/pipeline-base-image:latest
      env:
        - name: apikey
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: apikey    
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $(params.api) --apikey $apikey --no-region;
          cd /workspace;      
          echo "staring install";
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh;
          ibmcloud plugin install logging;
          echo "--------------------------------------------------------------------------------------------------";
          ibmcloud plugin install vpc-infrastructure;
           ibmcloud is vpc-create my-vpc --resource-group-id d0bb7c6f73be499599e27b54a0be9cae;
          
          
